url: "https://jdegbau.com"
baseurl: "/"
title: "Joshua DeGrasse-Baumann's Site"
highlighter: rouge
markdown: kramdown
paginate: 9
paginate_path: "/blog/:num/"
sass:
  style: compressed
  
# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: Joshua DeGrasse-Baumann
      layout: post
      permalink: /blog/:slug/
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      include_in_sitemap: true